// excel-formula-trainer/data.js
// Content catalog: levels, formulas, practice scenarios, and quiz questions.
// Values in grids are numbers or strings. Empty cells are omitted.
// Localization: each node may carry an `i18n` map { es, id, fr } overriding
// translatable fields. Formula NAMES and SYNTAX stay universal (Excel is English);
// string-literal EXPECTED/SOLUTION values are localized together so they stay consistent.

const LEVELS = [
  {
    id: 1,
    name: "Basics",
    icon: "🧮",
    tagline: "Add, average, and summarize numbers.",
    formulas: [
      {
        name: "SUM",
        syntax: "=SUM(number1, [number2], ...)",
        description: "Adds all the numbers in a range or list of arguments.",
        example: "=SUM(A1:A4)",
        result: "Adds the values in cells A1 through A4.",
        i18n: {
          es: { description: "Suma todos los números de un rango o lista de argumentos.", result: "Suma los valores de las celdas A1 a A4." },
          id: { description: "Menjumlahkan semua angka dalam sebuah rentang atau daftar argumen.", result: "Menjumlahkan nilai dari sel A1 hingga A4." },
          fr: { description: "Additionne tous les nombres d'une plage ou d'une liste d'arguments.", result: "Additionne les valeurs des cellules A1 à A4." },
        },
      },
      {
        name: "AVERAGE",
        syntax: "=AVERAGE(number1, [number2], ...)",
        description: "Returns the arithmetic mean of the numbers provided.",
        example: "=AVERAGE(B2:B6)",
        result: "The mean of the values in B2 through B6.",
        i18n: {
          es: { description: "Devuelve la media aritmética de los números proporcionados.", result: "La media de los valores de B2 a B6." },
          id: { description: "Mengembalikan rata-rata aritmetika dari angka-angka yang diberikan.", result: "Rata-rata dari nilai-nilai di B2 hingga B6." },
          fr: { description: "Renvoie la moyenne arithmétique des nombres fournis.", result: "La moyenne des valeurs de B2 à B6." },
        },
      },
      {
        name: "MIN",
        syntax: "=MIN(number1, [number2], ...)",
        description: "Returns the smallest (lowest) number in a set.",
        example: "=MIN(C1:C10)",
        result: "The lowest value in C1 through C10.",
        i18n: {
          es: { description: "Devuelve el número más pequeño (menor) de un conjunto.", result: "El valor más bajo de C1 a C10." },
          id: { description: "Mengembalikan angka terkecil dari satu kumpulan.", result: "Nilai terendah dari C1 hingga C10." },
          fr: { description: "Renvoie le plus petit nombre d'un ensemble.", result: "La plus petite valeur de C1 à C10." },
        },
      },
      {
        name: "MAX",
        syntax: "=MAX(number1, [number2], ...)",
        description: "Returns the largest (highest) number in a set.",
        example: "=MAX(C1:C10)",
        result: "The highest value in C1 through C10.",
        i18n: {
          es: { description: "Devuelve el número más grande (mayor) de un conjunto.", result: "El valor más alto de C1 a C10." },
          id: { description: "Mengembalikan angka terbesar dari satu kumpulan.", result: "Nilai tertinggi dari C1 hingga C10." },
          fr: { description: "Renvoie le plus grand nombre d'un ensemble.", result: "La plus grande valeur de C1 à C10." },
        },
      },
      {
        name: "COUNT",
        syntax: "=COUNT(value1, [value2], ...)",
        description: "Counts how many cells contain numbers (ignores text).",
        example: "=COUNT(A1:A8)",
        result: "The number of numeric cells in A1 through A8.",
        i18n: {
          es: { description: "Cuenta cuántas celdas contienen números (ignora el texto).", result: "La cantidad de celdas numéricas de A1 a A8." },
          id: { description: "Menghitung berapa banyak sel yang berisi angka (mengabaikan teks).", result: "Jumlah sel bernilai angka dari A1 hingga A8." },
          fr: { description: "Compte le nombre de cellules contenant des nombres (ignore le texte).", result: "Le nombre de cellules numériques de A1 à A8." },
        },
      },
      {
        name: "COUNTA",
        syntax: "=COUNTA(value1, [value2], ...)",
        description: "Counts how many cells are not empty (numbers or text).",
        example: "=COUNTA(A1:A8)",
        result: "The number of non-empty cells in A1 through A8.",
        i18n: {
          es: { description: "Cuenta cuántas celdas no están vacías (números o texto).", result: "La cantidad de celdas no vacías de A1 a A8." },
          id: { description: "Menghitung berapa banyak sel yang tidak kosong (angka atau teks).", result: "Jumlah sel tidak kosong dari A1 hingga A8." },
          fr: { description: "Compte le nombre de cellules non vides (nombres ou texte).", result: "Le nombre de cellules non vides de A1 à A8." },
        },
      },
    ],
    practices: [
      {
        id: "l1p1",
        title: "Total the sales",
        prompt: "In cell B5, write a formula that adds up the daily sales in B2:B4.",
        grid: { A1: "Day", B1: "Sales", A2: "Mon", B2: 120, A3: "Tue", B3: 85, A4: "Wed", B4: 97 },
        targetCell: "B5",
        expected: 302,
        hint: "Use SUM with the range B2:B4.",
        solution: "=SUM(B2:B4)",
        i18n: {
          es: { title: "Sumar las ventas", prompt: "En la celda B5, escribe una fórmula que sume las ventas diarias en B2:B4.", hint: "Usa SUM con el rango B2:B4." },
          id: { title: "Total penjualan", prompt: "Di sel B5, tulis rumus yang menjumlahkan penjualan harian di B2:B4.", hint: "Gunakan SUM dengan rentang B2:B4." },
          fr: { title: "Total des ventes", prompt: "Dans la cellule B5, écris une formule qui additionne les ventes quotidiennes en B2:B4.", hint: "Utilise SUM avec la plage B2:B4." },
        },
      },
      {
        id: "l1p2",
        title: "Find the best day",
        prompt: "In cell B6, write a formula that returns the highest sales value in B2:B4.",
        grid: { A1: "Day", B1: "Sales", A2: "Mon", B2: 120, A3: "Tue", B3: 85, A4: "Wed", B4: 97 },
        targetCell: "B6",
        expected: 120,
        hint: "MAX picks the largest number in a range.",
        solution: "=MAX(B2:B4)",
        i18n: {
          es: { title: "El mejor día", prompt: "En la celda B6, escribe una fórmula que devuelva la venta más alta en B2:B4.", hint: "MAX elige el número más grande de un rango." },
          id: { title: "Hari terbaik", prompt: "Di sel B6, tulis rumus yang mengembalikan penjualan tertinggi di B2:B4.", hint: "MAX memilih angka terbesar dari rentang." },
          fr: { title: "Le meilleur jour", prompt: "Dans B6, écris une formule qui renvoie la vente la plus élevée en B2:B4.", hint: "MAX prend le plus grand nombre d'une plage." },
        },
      },
      {
        id: "l1p3",
        title: "How many numbers?",
        prompt: "In cell A5, write a formula that counts the numeric cells in B2:B4.",
        grid: { A1: "Day", B1: "Sales", A2: "Mon", B2: 120, A3: "Tue", B3: 85, A4: "Wed", B4: 97, A5: "" },
        targetCell: "A5",
        expected: 3,
        hint: "COUNT only counts cells that contain numbers.",
        solution: "=COUNT(B2:B4)",
        i18n: {
          es: { title: "¿Cuántos números?", prompt: "En la celda A5, escribe una fórmula que cuente las celdas numéricas en B2:B4.", hint: "COUNT solo cuenta celdas con números." },
          id: { title: "Berapa banyak angka?", prompt: "Di sel A5, tulis rumus yang menghitung sel bernilai angka di B2:B4.", hint: "COUNT hanya menghitung sel yang berisi angka." },
          fr: { title: "Combien de nombres ?", prompt: "Dans A5, écris une formule qui compte les cellules numériques en B2:B4.", hint: "COUNT compte seulement les cellules contenant des nombres." },
        },
      },
      {
        id: "l1p4",
        title: "Count the entries",
        prompt: "In cell A9, write a formula that counts all non-empty cells in A2:A8.",
        grid: { A1: "Name", A2: "Ann", A3: "Bob", A4: "", A5: "Cy", A6: "Dan", A7: "", A8: "Eve", A9: "" },
        targetCell: "A9",
        expected: 5,
        hint: "COUNTA counts text and numbers, ignoring blanks.",
        solution: "=COUNTA(A2:A8)",
        i18n: {
          es: { title: "Cuenta las entradas", prompt: "En la celda A9, escribe una fórmula que cuente todas las celdas no vacías en A2:A8.", hint: "COUNTA cuenta texto y números, ignorando los espacios en blanco." },
          id: { title: "Hitung entri", prompt: "Di sel A9, tulis rumus yang menghitung semua sel tidak kosong di A2:A8.", hint: "COUNTA menghitung teks dan angka, mengabaikan sel kosong." },
          fr: { title: "Compter les entrées", prompt: "Dans A9, écris une formule qui compte toutes les cellules non vides en A2:A8.", hint: "COUNTA compte le texte et les nombres, ignorant les vides." },
        },
      },
    ],
    quizzes: [
      {
        id: "l1q1",
        type: "mc",
        prompt: "Which formula adds the numbers in cells A1, A2 and A3?",
        options: ["=ADD(A1:A3)", "=SUM(A1:A3)", "=TOTAL(A1:A3)", "=PLUS(A1:A3)"],
        answer: 1,
        i18n: {
          es: { prompt: "¿Qué fórmula suma los números en las celdas A1, A2 y A3?" },
          id: { prompt: "Rumus mana yang menjumlahkan angka di sel A1, A2, dan A3?" },
          fr: { prompt: "Quelle formule additionne les nombres des cellules A1, A2 et A3 ?" },
        },
      },
      {
        id: "l1q2",
        type: "mc",
        prompt: "What does =AVERAGE(10, 20, 30) return?",
        options: ["10", "20", "60", "30"],
        answer: 1,
        i18n: {
          es: { prompt: "¿Qué devuelve =AVERAGE(10, 20, 30)?" },
          id: { prompt: "Apa hasil =AVERAGE(10, 20, 30)?" },
          fr: { prompt: "Que renvoie =AVERAGE(10, 20, 30) ?" },
        },
      },
      {
        id: "l1q3",
        type: "mc",
        prompt: "=MIN(5, 9, 2, 7) returns which value?",
        options: ["5", "2", "9", "7"],
        answer: 1,
        i18n: {
          es: { prompt: "¿Qué devuelve =MIN(5, 9, 2, 7)?" },
          id: { prompt: "Apa hasil =MIN(5, 9, 2, 7)?" },
          fr: { prompt: "Que renvoie =MIN(5, 9, 2, 7) ?" },
        },
      },
      {
        id: "l1q4",
        type: "write",
        title: "Average the scores",
        prompt: "In cell B5, write a formula that averages the scores in B2:B4.",
        grid: { A1: "Student", B1: "Score", A2: "Ann", B2: 88, A3: "Bob", B3: 74, A4: "Cy", B4: 90, B5: "" },
        targetCell: "B5",
        expected: 84,
        solution: "=AVERAGE(B2:B4)",
        i18n: {
          es: { title: "Promedia las notas", prompt: "En B5, escribe una fórmula que promedie las notas en B2:B4." },
          id: { title: "Rata-rata nilai", prompt: "Di B5, tulis rumus yang merata-rata nilai di B2:B4." },
          fr: { title: "Moyenne des notes", prompt: "Dans B5, écris une formule qui fait la moyenne des notes en B2:B4." },
        },
      },
      {
        id: "l1q5",
        type: "mc",
        prompt: "What is the difference between COUNT and COUNTA?",
        options: ["COUNT counts text, COUNTA counts numbers", "COUNT counts numbers, COUNTA counts non-empty cells", "They are the same function", "COUNTA only counts text"],
        answer: 1,
        i18n: {
          es: { prompt: "¿Cuál es la diferencia entre COUNT y COUNTA?" },
          id: { prompt: "Apa perbedaan antara COUNT dan COUNTA?" },
          fr: { prompt: "Quelle est la différence entre COUNT et COUNTA ?" },
        },
      },
    ],
  },

  {
    id: 2,
    name: "Logic",
    icon: "🔀",
    tagline: "Make decisions with IF and comparisons.",
    formulas: [
      {
        name: "IF",
        syntax: "=IF(condition, value_if_true, value_if_false)",
        description: "Tests a condition and returns one value if TRUE, another if FALSE.",
        example: '=IF(B2>=60, "Pass", "Fail")',
        result: 'Returns "Pass" when B2 is 60 or more, otherwise "Fail".',
        i18n: {
          es: {
            description: "Evalúa una condición y devuelve un valor si es VERDADERO y otro si es FALSO.",
            example: '=IF(B2>=60, "Aprobado", "Suspenso")',
            result: 'Devuelve "Aprobado" si B2 es 60 o más, y "Suspenso" en caso contrario.',
          },
          id: {
            description: "Menguji suatu kondisi dan mengembalikan satu nilai jika BENAR, nilai lain jika SALAH.",
            example: '=IF(B2>=60, "Lulus", "Gagal")',
            result: 'Mengembalikan "Lulus" jika B2 bernilai 60 atau lebih, jika tidak "Gagal".',
          },
          fr: {
            description: "Teste une condition et renvoie une valeur si VRAI, une autre si FAUX.",
            example: '=IF(B2>=60, "Réussi", "Échec")',
            result: 'Renvoie "Réussi" si B2 vaut 60 ou plus, sinon "Échec".',
          },
        },
      },
      {
        name: "Comparison operators",
        syntax: "= , <> , > , < , >= , <=",
        description: "Used inside IF to compare values. = equals, <> not equal.",
        example: "=IF(A1>B1, A1, B1)",
        result: "Returns the larger of A1 and B1.",
        i18n: {
          es: {
            name: "Operadores de comparación",
            description: "Se usan dentro de SI para comparar valores. = igual, <> distinto.",
            result: "Devuelve el mayor entre A1 y B1.",
          },
          id: {
            name: "Operator perbandingan",
            description: "Digunakan di dalam IF untuk membandingkan nilai. = sama, <> tidak sama.",
            result: "Mengembalikan yang lebih besar dari A1 dan B1.",
          },
          fr: {
            name: "Opérateurs de comparaison",
            description: "Utilisés dans SI pour comparer des valeurs. = égal, <> différent.",
            result: "Renvoie le plus grand entre A1 et B1.",
          },
        },
      },
      {
        name: "AND / OR",
        syntax: "=AND(cond1, cond2)  |  =OR(cond1, cond2)",
        description: "Combine conditions. AND needs all true; OR needs at least one.",
        example: '=IF(AND(B2>=60, C2>=60), "Pass", "Fail")',
        result: 'Passes only when both B2 and C2 are 60 or more.',
        i18n: {
          es: {
            description: "Combina condiciones. AND requiere todas verdaderas; OR al menos una.",
            example: '=IF(AND(B2>=60, C2>=60), "Aprobado", "Suspenso")',
            result: "Aprueba solo cuando B2 y C2 son 60 o más.",
          },
          id: {
            description: "Menggabungkan kondisi. AND butuh semua benar; OR butuh minimal satu.",
            example: '=IF(AND(B2>=60, C2>=60), "Lulus", "Gagal")',
            result: "Lulus hanya bila B2 dan C2 bernilai 60 atau lebih.",
          },
          fr: {
            description: "Combine des conditions. AND exige tout vrai ; OR au moins une.",
            example: '=IF(AND(B2>=60, C2>=60), "Réussi", "Échec")',
            result: "Réussit seulement quand B2 et C2 valent 60 ou plus.",
          },
        },
      },
      {
        name: "IFERROR",
        syntax: "=IFERROR(value, value_if_error)",
        description: "Catches errors and returns a fallback value instead of an error.",
        example: '=IFERROR(A1/B1, "Error")',
        result: 'Returns the division, or "Error" if it fails (e.g. divide by zero).',
        i18n: {
          es: {
            description: "Captura errores y devuelve un valor alternativo en lugar de un error.",
            example: '=IFERROR(A1/B1, "Error")',
            result: 'Devuelve la división, o "Error" si falla (p. ej. dividir entre cero).',
          },
          id: {
            description: "Menangkap error dan mengembalikan nilai cadangan sebagai gantinya.",
            example: '=IFERROR(A1/B1, "Error")',
            result: 'Mengembalikan hasil bagi, atau "Error" jika gagal (mis. bagi nol).',
          },
          fr: {
            description: "Intercepte les erreurs et renvoie une valeur de remplacement au lieu d'une erreur.",
            example: '=IFERROR(A1/B1, "Erreur")',
            result: 'Renvoie la division, ou "Erreur" si elle échoue (ex. division par zéro).',
          },
        },
      },
    ],
    practices: [
      {
        id: "l2p1",
        title: "Pass or fail",
        prompt: 'In cell C2, write an IF formula that shows "Pass" if B2 is 60 or more, otherwise "Fail".',
        grid: { A1: "Student", B1: "Score", C1: "Result", A2: "Ann", B2: 72, C2: "" },
        targetCell: "C2",
        expected: "Pass",
        hint: '=IF(B2>=60, "Pass", "Fail")',
        solution: '=IF(B2>=60, "Pass", "Fail")',
        i18n: {
          es: {
            title: "Aprobar o reprobar",
            prompt: 'En C2, escribe una fórmula SI que muestre "Aprobado" si B2 es 60 o más, y "Suspenso" en caso contrario.',
            expected: "Aprobado",
            hint: '=IF(B2>=60, "Aprobado", "Suspenso")',
            solution: '=IF(B2>=60, "Aprobado", "Suspenso")',
          },
          id: {
            title: "Lulus atau gagal",
            prompt: 'Di C2, tulis rumus IF yang menampilkan "Lulus" jika B2 bernilai 60 atau lebih, dan "Gagal" jika tidak.',
            expected: "Lulus",
            hint: '=IF(B2>=60, "Lulus", "Gagal")',
            solution: '=IF(B2>=60, "Lulus", "Gagal")',
          },
          fr: {
            title: "Réussi ou échec",
            prompt: 'Dans C2, écris une formule SI qui affiche "Réussi" si B2 vaut 60 ou plus, sinon "Échec".',
            expected: "Réussi",
            hint: '=IF(B2>=60, "Réussi", "Échec")',
            solution: '=IF(B2>=60, "Réussi", "Échec")',
          },
        },
      },
      {
        id: "l2p2",
        title: "Pick the bigger",
        prompt: "In cell C1, write a formula that returns the larger of A1 and B1.",
        grid: { A1: 15, B1: 27, C1: "" },
        targetCell: "C1",
        expected: 27,
        hint: "Use IF with a > comparison, returning one cell or the other.",
        solution: "=IF(A1>B1, A1, B1)",
        i18n: {
          es: { title: "Elige el mayor", prompt: "En C1, escribe una fórmula que devuelva el mayor entre A1 y B1.", hint: "Usa SI con una comparación >, devolviendo una celda u otra." },
          id: { title: "Pilih yang lebih besar", prompt: "Di C1, tulis rumus yang mengembalikan yang lebih besar dari A1 dan B1.", hint: "Gunakan IF dengan perbandingan >, mengembalikan satu sel atau yang lain." },
          fr: { title: "Choisir le plus grand", prompt: "Dans C1, écris une formule qui renvoie le plus grand entre A1 et B1.", hint: "Utilise SI avec une comparaison >, renvoyant l'une ou l'autre cellule." },
        },
      },
      {
        id: "l2p3",
        title: "Safe division",
        prompt: 'In cell C2, divide A1 by B1 but show "Error" if the calculation fails (e.g. divide by zero).',
        grid: { A1: "Num", B1: "Den", C1: "Result", A2: 10, B2: 0, C2: "" },
        targetCell: "C2",
        expected: "Error",
        hint: '=IFERROR(A1/B1, "Error")',
        solution: '=IFERROR(A1/B1, "Error")',
        i18n: {
          es: {
            title: "División segura",
            prompt: 'En C2, divide A1 entre B1 pero muestra "Error" si el cálculo falla (p. ej. dividir entre cero).',
            expected: "Error",
            hint: '=IFERROR(A1/B1, "Error")',
            solution: '=IFERROR(A1/B1, "Error")',
          },
          id: {
            title: "Pembagian aman",
            prompt: 'Di C2, bagi A1 dengan B1 tetapi tampilkan "Error" jika perhitungan gagal (mis. bagi nol).',
            expected: "Error",
            hint: '=IFERROR(A1/B1, "Error")',
            solution: '=IFERROR(A1/B1, "Error")',
          },
          fr: {
            title: "Division sûre",
            prompt: 'Dans C2, divise A1 par B1 mais affiche "Erreur" si le calcul échoue (ex. division par zéro).',
            expected: "Erreur",
            hint: '=IFERROR(A1/B1, "Erreur")',
            solution: '=IFERROR(A1/B1, "Erreur")',
          },
        },
      },
    ],
    quizzes: [
      {
        id: "l2q1",
        type: "mc",
        prompt: 'What does =IF(5 > 3, "Yes", "No") return?',
        options: ['"Yes"', '"No"', "TRUE", "5"],
        answer: 0,
        i18n: {
          es: { prompt: '¿Qué devuelve =IF(5 > 3, "Yes", "No")?' },
          id: { prompt: 'Apa hasil =IF(5 > 3, "Yes", "No")?' },
          fr: { prompt: 'Que renvoie =IF(5 > 3, "Yes", "No") ?' },
        },
      },
      {
        id: "l2q2",
        type: "mc",
        prompt: "Which operator means 'not equal to' in Excel?",
        options: ["!=", "><", "<>", "=/="],
        answer: 2,
        i18n: {
          es: { prompt: "¿Qué operador significa 'distinto de' en Excel?" },
          id: { prompt: "Operator mana yang berarti 'tidak sama dengan' di Excel?" },
          fr: { prompt: "Quel opérateur signifie 'différent de' dans Excel ?" },
        },
      },
      {
        id: "l2q3",
        type: "write",
        title: "Bonus check",
        prompt: 'In cell C2, write an IF that shows "Bonus" if B2 is 100 or more, else "None".',
        grid: { A1: "Employee", B1: "Sales", C1: "Bonus?", A2: "Sam", B2: 100, C2: "" },
        targetCell: "C2",
        expected: "Bonus",
        solution: '=IF(B2>=100, "Bonus", "None")',
        i18n: {
          es: {
            title: "Verificación de bono",
            prompt: 'En C2, escribe un SI que muestre "Bono" si B2 es 100 o más, y "Nada" en caso contrario.',
            expected: "Bono",
            solution: '=IF(B2>=100, "Bono", "Nada")',
          },
          id: {
            title: "Cek bonus",
            prompt: 'Di C2, tulis IF yang menampilkan "Bonus" jika B2 bernilai 100 atau lebih, dan "Tidak" jika tidak.',
            expected: "Bonus",
            solution: '=IF(B2>=100, "Bonus", "Tidak")',
          },
          fr: {
            title: "Vérification de bonus",
            prompt: 'Dans C2, écris un SI qui affiche "Bonus" si B2 vaut 100 ou plus, sinon "Aucun".',
            expected: "Bonus",
            solution: '=IF(B2>=100, "Bonus", "Aucun")',
          },
        },
      },
      {
        id: "l2q4",
        type: "write",
        title: "Catch the error",
        prompt: 'In cell C2, divide A1 by B1 and show "Error" if it fails.',
        grid: { A1: "Num", B1: "Den", C1: "Result", A2: 5, B2: 0, C2: "" },
        targetCell: "C2",
        expected: "Error",
        solution: '=IFERROR(A1/B1, "Error")',
        i18n: {
          es: { title: "Captura el error", prompt: 'En C2, divide A1 entre B1 y muestra "Error" si falla.', expected: "Error", solution: '=IFERROR(A1/B1, "Error")' },
          id: { title: "Tangkap error", prompt: 'Di C2, bagi A1 dengan B1 dan tampilkan "Error" jika gagal.', expected: "Error", solution: '=IFERROR(A1/B1, "Error")' },
          fr: { title: "Intercepter l'erreur", prompt: 'Dans C2, divise A1 par B1 et affiche "Erreur" si cela échoue.', expected: "Erreur", solution: '=IFERROR(A1/B1, "Erreur")' },
        },
      },
    ],
  },

  {
    id: 3,
    name: "Text",
    icon: "🔤",
    tagline: "Join and shape text values.",
    formulas: [
      {
        name: "CONCAT",
        syntax: '=CONCAT(text1, [text2], ...)',
        description: "Joins two or more text strings into one.",
        example: '=CONCAT(A2, " ", B2)',
        result: "Combines first and last name with a space.",
        i18n: {
          es: { description: "Une dos o más cadenas de texto en una sola.", result: "Combina el nombre y apellido con un espacio." },
          id: { description: "Menggabungkan dua atau lebih teks menjadi satu.", result: "Menggabungkan nama depan dan belakang dengan spasi." },
          fr: { description: "Concatène deux chaînes de texte ou plus en une seule.", result: "Combine le prénom et le nom avec un espace." },
        },
      },
      {
        name: "Ampersand (&)",
        syntax: "=text1 & text2",
        description: "The & operator also joins text. Often quicker than CONCAT.",
        example: '=A2 & " " & B2',
        result: "Same result as CONCAT above.",
        i18n: {
          es: { description: "El operador & también une texto. A menudo más rápido que CONCAT.", result: "Mismo resultado que CONCAT arriba." },
          id: { description: "Operator & juga menggabungkan teks. Sering lebih cepat dari CONCAT.", result: "Hasil yang sama dengan CONCAT di atas." },
          fr: { description: "L'opérateur & concatène aussi du texte. Souvent plus rapide que CONCAT.", result: "Même résultat que CONCAT ci-dessus." },
        },
      },
      {
        name: "LEFT",
        syntax: "=LEFT(text, num_chars)",
        description: "Returns the first N characters from the left of a text.",
        example: "=LEFT(A2, 3)",
        result: "The first 3 characters of A2.",
        i18n: {
          es: { description: "Devuelve los primeros N caracteres desde la izquierda del texto.", result: "Los primeros 3 caracteres de A2." },
          id: { description: "Mengembalikan N karakter pertama dari kiri suatu teks.", result: "3 karakter pertama dari A2." },
          fr: { description: "Renvoie les N premiers caractères à gauche d'un texte.", result: "Les 3 premiers caracteres de A2." },
        },
      },
      {
        name: "RIGHT",
        syntax: "=RIGHT(text, num_chars)",
        description: "Returns the last N characters from the right of a text.",
        example: "=RIGHT(A2, 2)",
        result: "The last 2 characters of A2.",
        i18n: {
          es: { description: "Devuelve los últimos N caracteres desde la derecha del texto.", result: "Los últimos 2 caracteres de A2." },
          id: { description: "Mengembalikan N karakter terakhir dari kanan suatu teks.", result: "2 karakter terakhir dari A2." },
          fr: { description: "Renvoie les N derniers caractères à droite d'un texte.", result: "Les 2 derniers caracteres de A2." },
        },
      },
      {
        name: "UPPER / LOWER",
        syntax: "=UPPER(text)  |  =LOWER(text)",
        description: "Converts text to all uppercase or all lowercase.",
        example: "=UPPER(A2)",
        result: "A2 converted to uppercase.",
        i18n: {
          es: { description: "Convierte el texto a mayúsculas o minúsculas.", result: "A2 convertido a mayúsculas." },
          id: { description: "Mengubah teks menjadi semua huruf besar atau semua huruf kecil.", result: "A2 diubah menjadi huruf besar." },
          fr: { description: "Convertit le texte en majuscules ou en minuscules.", result: "A2 converti en majuscules." },
        },
      },
      {
        name: "LEN",
        syntax: "=LEN(text)",
        description: "Returns the number of characters in a text.",
        example: "=LEN(A2)",
        result: "The length of the text in A2.",
        i18n: {
          es: { description: "Devuelve la cantidad de caracteres de un texto.", result: "La longitud del texto en A2." },
          id: { description: "Mengembalikan jumlah karakter dalam suatu teks.", result: "Panjang teks di A2." },
          fr: { description: "Renvoie le nombre de caractères d'un texte.", result: "La longueur du texte en A2." },
        },
      },
      {
        name: "MID",
        syntax: "=MID(text, start_num, num_chars)",
        description: "Returns a substring from the middle of text, starting at a position.",
        example: "=MID(A2, 2, 3)",
        result: "3 characters of A2 starting at position 2.",
        i18n: {
          es: { description: "Devuelve una subcadena desde el medio del texto, a partir de una posición.", result: "3 caracteres de A2 empezando en la posición 2." },
          id: { description: "Mengembalikan subteks dari tengah teks, mulai dari posisi tertentu.", result: "3 karakter A2 mulai dari posisi 2." },
          fr: { description: "Renvoie une sous-chaîne du milieu du texte, à partir d'une position.", result: "3 caractères de A2 à partir de la position 2." },
        },
      },
      {
        name: "TRIM",
        syntax: "=TRIM(text)",
        description: "Removes extra spaces from text, leaving single spaces between words.",
        example: '=TRIM(A2)',
        result: "A2 with extra spaces removed.",
        i18n: {
          es: { description: "Elimina los espacios extras del texto, dejando espacios simples.", result: "A2 con los espacios extras eliminados." },
          id: { description: "Menghapus spasi berlebih dari teks, menyisakan spasi tunggal di antara kata.", result: "A2 dengan spasi berlebih dihapus." },
          fr: { description: "Supprime les espaces superflus du texte, ne laissant que des espaces simples.", result: "A2 avec les espaces superflus supprimés." },
        },
      },
      {
        name: "PROPER",
        syntax: "=PROPER(text)",
        description: "Capitalizes the first letter of each word in text.",
        example: '=PROPER(A2)',
        result: "A2 with each word capitalized.",
        i18n: {
          es: { description: "Pone en mayúscula la primera letra de cada palabra.", result: "A2 con cada palabra en mayúscula." },
          id: { description: "Membuat huruf pertama tiap kata menjadi kapital.", result: "A2 dengan setiap kata kapital." },
          fr: { description: "Met en majuscule la première lettre de chaque mot.", result: "A2 avec chaque mot en majuscule." },
        },
      },
      {
        name: "SUBSTITUTE",
        syntax: '=SUBSTITUTE(text, old_text, new_text)',
        description: "Replaces existing text with new text inside a string.",
        example: '=SUBSTITUTE(A2, "cat", "dog")',
        result: "A2 with every 'cat' changed to 'dog'.",
        i18n: {
          es: { description: "Reemplaza un texto existente por uno nuevo dentro de una cadena.", result: "A2 con cada 'cat' cambiado por 'dog'." },
          id: { description: "Mengganti teks tertentu dengan teks baru di dalam suatu string.", result: "A2 dengan setiap 'cat' diubah menjadi 'dog'." },
          fr: { description: "Remplace un texte existant par un nouveau dans une chaîne.", result: "A2 avec chaque 'cat' remplacé par 'dog'." },
        },
      },
    ],
    practices: [
      {
        id: "l3p1",
        title: "Full name",
        prompt: 'In cell C2, join the first name (A2) and last name (B2) with a space between.',
        grid: { A1: "First", B1: "Last", C1: "Full", A2: "Ada", B2: "Lovelace", C2: "" },
        targetCell: "C2",
        expected: "Ada Lovelace",
        hint: 'Try =A2 & " " & B2 or =CONCAT(A2, " ", B2).',
        solution: '=A2 & " " & B2',
        i18n: {
          es: { title: "Nombre completo", prompt: 'En C2, une el nombre (A2) y apellido (B2) con un espacio entre ellos.', hint: 'Prueba =A2 & " " & B2 o =CONCAT(A2, " ", B2).' },
          id: { title: "Nama lengkap", prompt: 'Di C2, gabungkan nama depan (A2) dan belakang (B2) dengan spasi di antaranya.', hint: 'Coba =A2 & " " & B2 atau =CONCAT(A2, " ", B2).' },
          fr: { title: "Nom complet", prompt: 'Dans C2, joins le prénom (A2) et le nom (B2) avec un espace.', hint: 'Essaie =A2 & " " & B2 ou =CONCAT(A2, " ", B2).' },
        },
      },
      {
        id: "l3p2",
        title: "Area code",
        prompt: "In cell B2, extract the first 3 characters of the phone number in A2.",
        grid: { A1: "Phone", B1: "Area", A2: "4155551234", B2: "" },
        targetCell: "B2",
        expected: "415",
        hint: "LEFT pulls characters from the start of text.",
        solution: "=LEFT(A2, 3)",
        i18n: {
          es: { title: "Código de área", prompt: "En B2, extrae los primeros 3 caracteres del número de teléfono en A2.", hint: "LEFT toma caracteres desde el inicio del texto." },
          id: { title: "Kode area", prompt: "Di B2, ambil 3 karakter pertama dari nomor telepon di A2.", hint: "LEFT mengambil karakter dari awal teks." },
          fr: { title: "Indicatif régional", prompt: "Dans B2, extrais les 3 premiers caractères du numéro de téléphone en A2.", hint: "LEFT prend les caractères au début du texte." },
        },
      },
      {
        id: "l3p3",
        title: "Measure the word",
        prompt: "In cell B2, find the number of characters in the text in A2.",
        grid: { A1: "Word", B1: "Length", A2: "Excel", B2: "" },
        targetCell: "B2",
        expected: 5,
        hint: "LEN counts characters (letters).",
        solution: "=LEN(A2)",
        i18n: {
          es: { title: "Mide la palabra", prompt: "En B2, encuentra la cantidad de caracteres del texto en A2.", hint: "LEN cuenta caracteres (letras)." },
          id: { title: "Ukur kata", prompt: "Di B2, temukan jumlah karakter dalam teks di A2.", hint: "LEN menghitung karakter (huruf)." },
          fr: { title: "Mesure le mot", prompt: "Dans B2, trouve le nombre de caractères du texte en A2.", hint: "LEN compte les caractères (lettres)." },
        },
      },
      {
        id: "l3p4",
        title: "Grab the middle",
        prompt: "In cell B2, extract 2 characters from A2 starting at position 2.",
        grid: { A1: "Code", B1: "Mid", A2: "ABCD", B2: "" },
        targetCell: "B2",
        expected: "BC",
        hint: "MID(text, start, length) is 1-based.",
        solution: "=MID(A2, 2, 2)",
        i18n: {
          es: { title: "Toma el medio", prompt: "En B2, extrae 2 caracteres de A2 empezando en la posición 2.", hint: "MID(texto, inicio, longitud) empieza en 1." },
          id: { title: "Ambil tengah", prompt: "Di B2, ambil 2 karakter dari A2 mulai dari posisi 2.", hint: "MID(teks, awal, panjang) berbasis 1." },
          fr: { title: "Prends le milieu", prompt: "Dans B2, extrais 2 caractères de A2 à partir de la position 2.", hint: "MID(texte, début, longueur) commence à 1." },
        },
      },
      {
        id: "l3p5",
        title: "Title case it",
        prompt: "In cell B2, capitalize the first letter of each word in A2.",
        grid: { A1: "Name", B1: "Proper", A2: "ada lovelace", B2: "" },
        targetCell: "B2",
        expected: "Ada Lovelace",
        hint: "PROPER capitalizes each word.",
        solution: '=PROPER(A2)',
        i18n: {
          es: { title: "Pon título", prompt: "En B2, pon en mayúscula la primera letra de cada palabra en A2.", hint: "PROPER capitaliza cada palabra." },
          id: { title: "Huruf kapital tiap kata", prompt: "Di B2, buat huruf pertama tiap kata di A2 menjadi kapital.", hint: "PROPER membuat tiap kata kapital." },
          fr: { title: "Majuscules de titre", prompt: "Dans B2, met en majuscule la première lettre de chaque mot en A2.", hint: "PROPER met chaque mot en majuscule." },
        },
      },
      {
        id: "l3p6",
        title: "Tidy the text",
        prompt: "In cell B2, remove the extra spaces from the text in A2.",
        grid: { A1: "Messy", B1: "Clean", A2: "  hello   world  ", B2: "" },
        targetCell: "B2",
        expected: "hello world",
        hint: "TRIM collapses repeated spaces.",
        solution: '=TRIM(A2)',
        i18n: {
          es: { title: "Arregla el texto", prompt: "En B2, elimina los espacios extras del texto en A2.", hint: "TRIM colapsa los espacios repetidos." },
          id: { title: "Rapikan teks", prompt: "Di B2, hapus spasi berlebih dari teks di A2.", hint: "TRIM merapatkan spasi berulang." },
          fr: { title: "Nettoie le texte", prompt: "Dans B2, supprime les espaces superflus du texte en A2.", hint: "TRIM réduit les espaces répétés." },
        },
      },
      {
        id: "l3p7",
        title: "Swap the word",
        prompt: "In cell B2, replace every 'cat' in A2 with 'dog'.",
        grid: { A1: "Text", B1: "New", A2: "the cat sat", B2: "" },
        targetCell: "B2",
        expected: "the dog sat",
        hint: "SUBSTITUTE(text, old, new) replaces all matches.",
        solution: '=SUBSTITUTE(A2, "cat", "dog")',
        i18n: {
          es: { title: "Cambia la palabra", prompt: "En B2, reemplaza cada 'cat' en A2 por 'dog'.", hint: "SUBSTITUTE(texto, viejo, nuevo) reemplaza todas las coincidencias." },
          id: { title: "Ganti kata", prompt: "Di B2, ganti setiap 'cat' di A2 dengan 'dog'.", hint: "SUBSTITUTE(teks, lama, baru) mengganti semua kemunculan." },
          fr: { title: "Change le mot", prompt: "Dans B2, remplace chaque 'cat' dans A2 par 'dog'.", hint: "SUBSTITUTE(texte, ancien, nouveau) remplace toutes les occurrences." },
        },
      },
    ],
    quizzes: [
      {
        id: "l3q1",
        type: "mc",
        prompt: 'What does =CONCAT("Hi", " ", "There") return?',
        options: ['"Hi There"', '"HiThere"', '"Hi There "', '"Hi+There"'],
        answer: 0,
        i18n: {
          es: { prompt: '¿Qué devuelve =CONCAT("Hi", " ", "There")?' },
          id: { prompt: 'Apa hasil =CONCAT("Hi", " ", "There")?' },
          fr: { prompt: 'Que renvoie =CONCAT("Hi", " ", "There") ?' },
        },
      },
      {
        id: "l3q2",
        type: "mc",
        prompt: "Which formula returns the last 2 characters of A1?",
        options: ["=LEFT(A1, 2)", "=RIGHT(A1, 2)", "=END(A1, 2)", "=TAIL(A1, 2)"],
        answer: 1,
        i18n: {
          es: { prompt: "¿Qué fórmula devuelve los últimos 2 caracteres de A1?" },
          id: { prompt: "Rumus mana yang mengembalikan 2 karakter terakhir dari A1?" },
          fr: { prompt: "Quelle formule renvoie les 2 derniers caractères de A1 ?" },
        },
      },
      {
        id: "l3q3",
        type: "write",
        title: "Lowercase it",
        prompt: "In cell B2, convert the text in A2 to lowercase.",
        grid: { A1: "Name", B1: "Lower", A2: "EXCEL", B2: "" },
        targetCell: "B2",
        expected: "excel",
        solution: "=LOWER(A2)",
        i18n: {
          es: { title: "En minúsculas", prompt: "En B2, convierte el texto de A2 a minúsculas." },
          id: { title: "Huruf kecil", prompt: "Di B2, ubah teks A2 menjadi huruf kecil." },
          fr: { title: "En minuscules", prompt: "Dans B2, convertis le texte de A2 en minuscules." },
        },
      },
      {
        id: "l3q4",
        type: "mc",
        prompt: 'What does =LEN("Excel") return?',
        options: ["5", "6", "4", "0"],
        answer: 0,
        i18n: {
          es: { prompt: '¿Qué devuelve =LEN("Excel")?' },
          id: { prompt: 'Apa hasil =LEN("Excel")?' },
          fr: { prompt: 'Que renvoie =LEN("Excel") ?' },
        },
      },
      {
        id: "l3q5",
        type: "write",
        title: "Middle extract",
        prompt: "In cell B2, get 3 characters from A2 starting at position 3.",
        grid: { A1: "Text", B1: "Mid", A2: "abcdef", B2: "" },
        targetCell: "B2",
        expected: "cde",
        solution: "=MID(A2, 3, 3)",
        i18n: {
          es: { title: "Extrae del medio", prompt: "En B2, toma 3 caracteres de A2 empezando en la posición 3.", solution: "=MID(A2, 3, 3)" },
          id: { title: "Ambil tengah", prompt: "Di B2, ambil 3 karakter dari A2 mulai posisi 3.", solution: "=MID(A2, 3, 3)" },
          fr: { title: "Extrait du milieu", prompt: "Dans B2, prends 3 caractères de A2 à partir de la position 3.", solution: "=MID(A2, 3, 3)" },
        },
      },
      {
        id: "l3q6",
        type: "mc",
        prompt: "Which function capitalizes the first letter of each word?",
        options: ["PROPER", "TRIM", "LEN", "MID"],
        answer: 0,
        i18n: {
          es: { prompt: "¿Qué función pone en mayúscula la primera letra de cada palabra?" },
          id: { prompt: "Fungsi mana yang membuat huruf pertama tiap kata menjadi kapital?" },
          fr: { prompt: "Quelle fonction met en majuscule la première lettre de chaque mot ?" },
        },
      },
    ],
  },

  {
    id: 4,
    name: "Numbers",
    icon: "🔢",
    tagline: "Round and reshape numbers.",
    formulas: [
      {
        name: "ROUND",
        syntax: "=ROUND(number, num_digits)",
        description: "Rounds a number to a given number of digits. 0 = whole number, 2 = cents.",
        example: "=ROUND(3.14159, 2)",
        result: "3.14",
        i18n: {
          es: { description: "Redondea un número a una cantidad de decimales. 0 = entero, 2 = centavos.", result: "3.14" },
          id: { description: "Membulatkan angka ke sejumlah digit. 0 = bilangan bulat, 2 = sen.", result: "3.14" },
          fr: { description: "Arrondit un nombre à un nombre de décimales. 0 = entier, 2 = centimes.", result: "3.14" },
        },
      },
      {
        name: "ABS",
        syntax: "=ABS(number)",
        description: "Returns the absolute (always positive) value of a number.",
        example: "=ABS(-7)",
        result: "7",
        i18n: {
          es: { description: "Devuelve el valor absoluto (siempre positivo) de un número.", result: "7" },
          id: { description: "Mengembalikan nilai absolut (selalu positif) dari sebuah angka.", result: "7" },
          fr: { description: "Renvoie la valeur absolue (toujours positive) d'un nombre.", result: "7" },
        },
      },
      {
        name: "INT",
        syntax: "=INT(number)",
        description: "Rounds a number down to the nearest whole number.",
        example: "=INT(4.9)",
        result: "4",
        i18n: {
          es: { description: "Redondea un número hacia abajo al entero más cercano.", result: "4" },
          id: { description: "Membulatkan angka ke bawah ke bilangan bulat terdekat.", result: "4" },
          fr: { description: "Arrondit un nombre à l'entier inférieur le plus proche.", result: "4" },
        },
      },
      {
        name: "ROUNDUP",
        syntax: "=ROUNDUP(number, num_digits)",
        description: "Rounds a number up, away from zero.",
        example: "=ROUNDUP(2.1, 0)",
        result: "3",
        i18n: {
          es: { description: "Redondea un número hacia arriba, alejándose de cero.", result: "3" },
          id: { description: "Membulatkan angka ke atas, menjauhi nol.", result: "3" },
          fr: { description: "Arrondit un nombre vers le haut, s'éloignant de zéro.", result: "3" },
        },
      },
      {
        name: "ROUNDDOWN",
        syntax: "=ROUNDDOWN(number, num_digits)",
        description: "Rounds a number down, toward zero.",
        example: "=ROUNDDOWN(2.9, 0)",
        result: "2",
        i18n: {
          es: { description: "Redondea un número hacia abajo, hacia cero.", result: "2" },
          id: { description: "Membulatkan angka ke bawah, menuju nol.", result: "2" },
          fr: { description: "Arrondit un nombre vers le bas, vers zéro.", result: "2" },
        },
      },
      {
        name: "MOD",
        syntax: "=MOD(number, divisor)",
        description: "Returns the remainder after a number is divided by a divisor.",
        example: "=MOD(10, 3)",
        result: "1",
        i18n: {
          es: { description: "Devuelve el resto de dividir un número por un divisor.", result: "1" },
          id: { description: "Mengembalikan sisa bagi sebuah angka dengan pembagi.", result: "1" },
          fr: { description: "Renvoie le reste de la division d'un nombre par un diviseur.", result: "1" },
        },
      },
      {
        name: "POWER",
        syntax: "=POWER(number, power)",
        description: "Raises a number to a given power.",
        example: "=POWER(2, 8)",
        result: "256",
        i18n: {
          es: { description: "Eleva un número a una potencia dada.", result: "256" },
          id: { description: "Memangkatkan angka ke sebuah pangkat tertentu.", result: "256" },
          fr: { description: "Élève un nombre à une puissance donnée.", result: "256" },
        },
      },
      {
        name: "SQRT",
        syntax: "=SQRT(number)",
        description: "Returns the square root of a number.",
        example: "=SQRT(16)",
        result: "4",
        i18n: {
          es: { description: "Devuelve la raíz cuadrada de un número.", result: "4" },
          id: { description: "Mengembalikan akar kuadrat dari suatu angka.", result: "4" },
          fr: { description: "Renvoie la racine carrée d'un nombre.", result: "4" },
        },
      },
    ],
    practices: [
      {
        id: "l4p1",
        title: "Round to cents",
        prompt: "In cell B2, round the value in A2 to 2 decimal places.",
        grid: { A1: "Price", B1: "Rounded", A2: 9.8765, B2: "" },
        targetCell: "B2",
        expected: 9.88,
        hint: "ROUND(number, 2) keeps two decimals.",
        solution: "=ROUND(A2, 2)",
        i18n: {
          es: { title: "Redondear a centavos", prompt: "En B2, redondea el valor de A2 a 2 decimales.", hint: "ROUND(número, 2) mantiene dos decimales." },
          id: { title: "Bulatkan ke sen", prompt: "Di B2, bulatkan nilai A2 ke 2 angka desimal.", hint: "ROUND(angka, 2) mempertahankan dua desimal." },
          fr: { title: "Arrondir aux centimes", prompt: "Dans B2, arrondis la valeur de A2 à 2 décimales.", hint: "ROUND(nombre, 2) garde deux décimales." },
        },
      },
      {
        id: "l4p2",
        title: "Make it positive",
        prompt: "In cell B2, return the absolute value of A2.",
        grid: { A1: "Change", B1: "Abs", A2: -42, B2: "" },
        targetCell: "B2",
        expected: 42,
        hint: "ABS removes the minus sign.",
        solution: "=ABS(A2)",
        i18n: {
          es: { title: "Hazlo positivo", prompt: "En B2, devuelve el valor absoluto de A2.", hint: "ABS quita el signo menos." },
          id: { title: "Jadikan positif", prompt: "Di B2, kembalikan nilai absolut dari A2.", hint: "ABS menghilangkan tanda minus." },
          fr: { title: "Rendez-le positif", prompt: "Dans B2, renvoie la valeur absolue de A2.", hint: "ABS retire le signe moins." },
        },
      },
      {
        id: "l4p3",
        title: "Round up",
        prompt: "In cell B2, round the value in A2 up to the next whole number.",
        grid: { A1: "Value", B1: "Up", A2: 2.1, B2: "" },
        targetCell: "B2",
        expected: 3,
        hint: "ROUNDUP never rounds down.",
        solution: "=ROUNDUP(A2, 0)",
        i18n: {
          es: { title: "Redondear hacia arriba", prompt: "En B2, redondea el valor de A2 al siguiente número entero.", hint: "ROUNDUP nunca redondea hacia abajo." },
          id: { title: "Bulatkan ke atas", prompt: "Di B2, bulatkan nilai A2 ke bilangan bulat berikutnya.", hint: "ROUNDUP tidak pernah membulatkan ke bawah." },
          fr: { title: "Arrondir au supérieur", prompt: "Dans B2, arrondis la valeur de A2 au nombre entier supérieur.", hint: "ROUNDUP n'arrondit jamais vers le bas." },
        },
      },
      {
        id: "l4p4",
        title: "Round down",
        prompt: "In cell B2, round the value in A2 down to the nearest whole number.",
        grid: { A1: "Value", B1: "Down", A2: 2.9, B2: "" },
        targetCell: "B2",
        expected: 2,
        hint: "ROUNDDOWN never rounds up.",
        solution: "=ROUNDDOWN(A2, 0)",
        i18n: {
          es: { title: "Redondear hacia abajo", prompt: "En B2, redondea el valor de A2 al número entero más cercano por debajo.", hint: "ROUNDDOWN nunca redondea hacia arriba." },
          id: { title: "Bulatkan ke bawah", prompt: "Di B2, bulatkan nilai A2 ke bilangan bulat terdekat di bawahnya.", hint: "ROUNDDOWN tidak pernah membulatkan ke atas." },
          fr: { title: "Arrondir au inférieur", prompt: "Dans B2, arrondis la valeur de A2 à l'entier inférieur le plus proche.", hint: "ROUNDDOWN n'arrondit jamais vers le haut." },
        },
      },
      {
        id: "l4p5",
        title: "Find the remainder",
        prompt: "In cell B3, find the remainder when A2 is divided by B2.",
        grid: { A1: "Dividend", B1: "Divisor", A2: 10, B2: 3, A3: "Remainder", B3: "" },
        targetCell: "B3",
        expected: 1,
        hint: "MOD(number, divisor) returns the left-over.",
        solution: "=MOD(A2, B2)",
        i18n: {
          es: { title: "Encuentra el resto", prompt: "En B3, halla el resto de A2 dividido por B2.", hint: "MOD(número, divisor) devuelve lo que sobra." },
          id: { title: "Cari sisa", prompt: "Di B3, temukan sisa bagi A2 dengan B2.", hint: "MOD(angka, pembagi) mengembalikan sisa." },
          fr: { title: "Trouve le reste", prompt: "Dans B3, trouve le reste de A2 divisé par B2.", hint: "MOD(nombre, diviseur) renvoie ce qui reste." },
        },
      },
      {
        id: "l4p6",
        title: "Raise to power",
        prompt: "In cell B3, raise A2 to the power of B2.",
        grid: { A1: "Base", B1: "Exponent", A2: 2, B2: 8, A3: "Result", B3: "" },
        targetCell: "B3",
        expected: 256,
        hint: "POWER(base, exponent) is repeated multiplication.",
        solution: "=POWER(A2, B2)",
        i18n: {
          es: { title: "Eleva a una potencia", prompt: "En B3, eleva A2 a la potencia B2.", hint: "POWER(base, exponente) es multiplicación repetida." },
          id: { title: "Pangkatkan", prompt: "Di B3, pangkatkan A2 dengan B2.", hint: "POWER(basis, pangkat) adalah perkalian berulang." },
          fr: { title: "Élève à la puissance", prompt: "Dans B3, élève A2 à la puissance B2.", hint: "POWER(base, exposant) est une multiplication répétée." },
        },
      },
      {
        id: "l4p7",
        title: "Square root",
        prompt: "In cell B2, find the square root of A2.",
        grid: { A1: "Number", B1: "Root", A2: 16, B2: "" },
        targetCell: "B2",
        expected: 4,
        hint: "SQRT finds the number that, times itself, gives the input.",
        solution: "=SQRT(A2)",
        i18n: {
          es: { title: "Raíz cuadrada", prompt: "En B2, encuentra la raíz cuadrada de A2.", hint: "SQRT halla el número que, por sí mismo, da el valor." },
          id: { title: "Akar kuadrat", prompt: "Di B2, temukan akar kuadrat dari A2.", hint: "SQRT mencari angka yang jika dikalikan diri sendiri menghasilkan nilai tersebut." },
          fr: { title: "Racine carrée", prompt: "Dans B2, trouve la racine carrée de A2.", hint: "SQRT trouve le nombre qui, multiplié par lui-même, donne la valeur." },
        },
      },
    ],
    quizzes: [
      {
        id: "l4q1",
        type: "mc",
        prompt: "=ROUND(2.675, 2) is closest to:",
        options: ["2.67", "2.68", "2.7", "3"],
        answer: 1,
        i18n: {
          es: { prompt: "=ROUND(2.675, 2) está más cerca de:" },
          id: { prompt: "=ROUND(2.675, 2) paling dekat dengan:" },
          fr: { prompt: "=ROUND(2.675, 2) est proche de :" },
        },
      },
      {
        id: "l4q2",
        type: "mc",
        prompt: "=INT(7.9) returns:",
        options: ["7", "8", "7.9", "0"],
        answer: 0,
        i18n: {
          es: { prompt: "=INT(7.9) devuelve:" },
          id: { prompt: "=INT(7.9) menghasilkan:" },
          fr: { prompt: "=INT(7.9) renvoie :" },
        },
      },
      {
        id: "l4q3",
        type: "write",
        title: "Whole number",
        prompt: "In cell B2, round the value in A2 down to a whole number.",
        grid: { A1: "Value", B1: "Integer", A2: 15.99, B2: "" },
        targetCell: "B2",
        expected: 15,
        solution: "=INT(A2)",
        i18n: {
          es: { title: "Número entero", prompt: "En B2, redondea el valor de A2 al entero inferior." },
          id: { title: "Bilangan bulat", prompt: "Di B2, bulatkan nilai A2 ke bawah ke bilangan bulat." },
          fr: { title: "Nombre entier", prompt: "Dans B2, arrondis la valeur de A2 à l'entier inférieur." },
        },
      },
      {
        id: "l4q4",
        type: "mc",
        prompt: "=MOD(10, 3) returns:",
        options: ["3", "1", "0", "10"],
        answer: 1,
        i18n: {
          es: { prompt: "=MOD(10, 3) devuelve:" },
          id: { prompt: "=MOD(10, 3) menghasilkan:" },
          fr: { prompt: "=MOD(10, 3) renvoie :" },
        },
      },
      {
        id: "l4q5",
        type: "mc",
        prompt: "=POWER(2, 8) returns:",
        options: ["10", "16", "256", "64"],
        answer: 2,
        i18n: {
          es: { prompt: "=POWER(2, 8) devuelve:" },
          id: { prompt: "=POWER(2, 8) menghasilkan:" },
          fr: { prompt: "=POWER(2, 8) renvoie :" },
        },
      },
      {
        id: "l4q6",
        type: "write",
        title: "Round up to tens",
        prompt: "In cell B2, round A2 up to the nearest 10 (use a negative number of digits).",
        grid: { A1: "Value", B1: "Up10", A2: 14, B2: "" },
        targetCell: "B2",
        expected: 20,
        solution: "=ROUNDUP(A2, -1)",
        i18n: {
          es: { title: "Redondear a decenas", prompt: "En B2, redondea A2 hacia arriba a la decena más cercana (usa un número negativo de decimales).", solution: "=ROUNDUP(A2, -1)" },
          id: { title: "Bulatkan ke puluhan", prompt: "Di B2, bulatkan A2 ke atas ke puluhan terdekat (gunakan angka desimal negatif).", solution: "=ROUNDUP(A2, -1)" },
          fr: { title: "Arrondir aux dizaines", prompt: "Dans B2, arrondis A2 au supérieur à la dizaine la plus proche (utilise un nombre de décimales négatif).", solution: "=ROUNDUP(A2, -1)" },
        },
      },
    ],
  },

  {
    id: 5,
    name: "Lookups",
    icon: "🔎",
    tagline: "Find data across a table with VLOOKUP.",
    formulas: [
      {
        name: "VLOOKUP",
        syntax: "=VLOOKUP(lookup_value, table_array, col_index_num, [range_lookup])",
        description: "Searches the first column of a table for a value and returns a value from another column in the same row.",
        example: '=VLOOKUP("Apple", A2:C10, 2, FALSE)',
        result: "Finds 'Apple' in column A and returns the matching value from column 2 (B).",
        i18n: {
          es: { description: "Busca un valor en la primera columna de una tabla y devuelve un valor de otra columna en la misma fila.", result: "Busca 'Apple' en la columna A y devuelve el valor correspondiente de la columna 2 (B)." },
          id: { description: "Mencari nilai pada kolom pertama tabel dan mengembalikan nilai dari kolom lain di baris yang sama.", result: "Menemukan 'Apple' di kolom A dan mengembalikan nilai yang cocok dari kolom 2 (B)." },
          fr: { description: "Recherche une valeur dans la première colonne d'un tableau et renvoie une valeur d'une autre colonne sur la même ligne.", result: "Trouve 'Apple' dans la colonne A et renvoie la valeur correspondante de la colonne 2 (B)." },
        },
      },
      {
        name: "range_lookup",
        syntax: "FALSE  (or 0) = exact match  |  TRUE = nearest",
        description: "Usually set to FALSE for exact matches, which is what beginners need most.",
        example: "=VLOOKUP(101, A2:C50, 3, FALSE)",
        result: "Finds ID 101 and returns column 3 for that row.",
        i18n: {
          es: {
            name: "coincidencia",
            description: "Normalmente se usa FALSE para coincidencia exacta, lo que los principiantes necesitan.",
            result: "Busca la ID 101 y devuelve la columna 3 de esa fila.",
          },
          id: {
            name: "cocok",
            description: "Biasanya diatur FALSE untuk kecocokan tepat, yang paling dibutuhkan pemula.",
            result: "Menemukan ID 101 dan mengembalikan kolom 3 untuk baris tersebut.",
          },
          fr: {
            name: "correspondance",
            description: "En général on met FALSE pour une correspondance exacte, ce dont les débutants ont besoin.",
            result: "Trouve l'ID 101 et renvoie la colonne 3 de cette ligne.",
          },
        },
      },
      {
        name: "HLOOKUP",
        syntax: "=HLOOKUP(lookup_value, table_array, row_index_num, [range_lookup])",
        description: "Like VLOOKUP but searches the first ROW of a table and returns a value from a row below it.",
        example: '=HLOOKUP("Price", A1:E3, 2, FALSE)',
        result: "Finds the 'Price' column across the top row and returns the value from row 2.",
        i18n: {
          es: { description: "Como VLOOKUP pero busca en la primera FILA de una tabla y devuelve un valor de una fila inferior.", result: "Encuentra la columna 'Price' en la fila superior y devuelve el valor de la fila 2." },
          id: { description: "Seperti VLOOKUP tetapi mencari pada BARIS pertama tabel dan mengembalikan nilai dari baris di bawahnya.", result: "Menemukan kolom 'Price' di baris teratas dan mengembalikan nilai dari baris 2." },
          fr: { description: "Comme VLOOKUP mais recherche dans la première LIGNE d'un tableau et renvoie une valeur d'une ligne située en dessous.", result: "Trouve la colonne 'Price' sur la ligne du haut et renvoie la valeur de la ligne 2." },
        },
      },
      {
        name: "INDEX",
        syntax: "=INDEX(array, row_num, [col_num])",
        description: "Returns the value at a given row and column position inside a range. Often paired with MATCH.",
        example: "=INDEX(C2:C5, 2)",
        result: "Returns the 2nd item in the range C2:C5.",
        i18n: {
          es: { description: "Devuelve el valor en una posición de fila y columna dentro de un rango. Suele combinarse con MATCH.", result: "Devuelve el 2º elemento del rango C2:C5." },
          id: { description: "Mengembalikan nilai pada posisi baris dan kolom tertentu di dalam suatu rentang. Sering dipasangkan dengan MATCH.", result: "Mengembalikan item ke-2 pada rentang C2:C5." },
          fr: { description: "Renvoie la valeur à une position de ligne et de colonne donnée dans une plage. Souvent associé à MATCH.", result: "Renvoie le 2e élément de la plage C2:C5." },
        },
      },
      {
        name: "MATCH",
        syntax: "=MATCH(lookup_value, lookup_array, [match_type])",
        description: "Returns the relative POSITION of a value in a row or column. Use 0 for an exact match.",
        example: '=MATCH("Pear", A2:A5, 0)',
        result: "Finds 'Pear' and returns its position (2) within A2:A5.",
        i18n: {
          es: { description: "Devuelve la POSICIÓN relativa de un valor en una fila o columna. Usa 0 para coincidencia exacta.", result: "Encuentra 'Pear' y devuelve su posición (2) dentro de A2:A5." },
          id: { description: "Mengembalikan POSISI relatif suatu nilai dalam sebuah baris atau kolom. Gunakan 0 untuk kecocokan tepat.", result: "Menemukan 'Pear' dan mengembalikan posisinya (2) dalam A2:A5." },
          fr: { description: "Renvoie la POSITION relative d'une valeur dans une ligne ou colonne. Utilisez 0 pour une correspondance exacte.", result: "Trouve 'Pear' et renvoie sa position (2) dans A2:A5." },
        },
      },
      {
        name: "INDEX-MATCH",
        syntax: "=INDEX(result_range, MATCH(lookup_value, lookup_range, 0))",
        description: "The flexible alternative to VLOOKUP: MATCH finds the row, INDEX returns the value. It can look to the LEFT.",
        example: '=INDEX(C2:C5, MATCH(F2, A2:A5, 0))',
        result: "Finds the row for F2 in A2:A5, then returns the matching value from C2:C5.",
        i18n: {
          es: { description: "La alternativa flexible a VLOOKUP: MATCH encuentra la fila y INDEX devuelve el valor. Puede buscar a la IZQUIERDA.", result: "Encuentra la fila de F2 en A2:A5 y devuelve el valor correspondiente de C2:C5." },
          id: { description: "Alternatif fleksibel dari VLOOKUP: MATCH mencari barisnya dan INDEX mengembalikan nilainya. Bisa mencari ke KIRI.", result: "Menemukan baris F2 di A2:A5, lalu mengembalikan nilai yang cocok dari C2:C5." },
          fr: { description: "L'alternative flexible à VLOOKUP : MATCH trouve la ligne et INDEX renvoie la valeur. Elle peut chercher vers la GAUCHE.", result: "Trouve la ligne de F2 dans A2:A5, puis renvoie la valeur correspondante de C2:C5." },
        },
      },
    ],
    practices: [
      {
        id: "l5p1",
        title: "Find the price",
        prompt: 'In cell G2, use VLOOKUP to find the price of "Pear" from the table A2:C5, returning column 2 with an exact match.',
        grid: {
          A1: "Fruit", B1: "Price", C1: "Stock",
          A2: "Apple", B2: 1.2, C2: 50,
          A3: "Pear", B3: 1.5, C3: 30,
          A4: "Plum", B4: 0.9, C4: 80,
          A5: "Kiwi", B5: 2.0, C5: 25,
          F1: "Lookup", G1: "Result", F2: "Pear", G2: "",
        },
        targetCell: "G2",
        expected: 1.5,
        hint: "=VLOOKUP(F2, A2:C5, 2, FALSE)",
        solution: "=VLOOKUP(F2, A2:C5, 2, FALSE)",
        i18n: {
          es: { title: "Encontrar el precio", prompt: 'En G2, usa VLOOKUP para encontrar el precio de "Pear" en la tabla A2:C5, devolviendo la columna 2 con coincidencia exacta.', hint: "=VLOOKUP(F2, A2:C5, 2, FALSE)" },
          id: { title: "Temukan harga", prompt: 'Di G2, gunakan VLOOKUP untuk menemukan harga "Pear" dari tabel A2:C5, mengembalikan kolom 2 dengan kecocokan tepat.', hint: "=VLOOKUP(F2, A2:C5, 2, FALSE)" },
          fr: { title: "Trouver le prix", prompt: 'Dans G2, utilise VLOOKUP pour trouver le prix de "Pear" dans le tableau A2:C5, en renvoyant la colonne 2 avec correspondance exacte.', hint: "=VLOOKUP(F2, A2:C5, 2, FALSE)" },
        },
      },
      {
        id: "l5p2",
        title: "Find the stock",
        prompt: 'In cell G2, use VLOOKUP to find the stock (column 3) of the fruit named in F2 from table A2:C5, exact match.',
        grid: {
          A1: "Fruit", B1: "Price", C1: "Stock",
          A2: "Apple", B2: 1.2, C2: 50,
          A3: "Pear", B3: 1.5, C3: 30,
          A4: "Plum", B4: 0.9, C4: 80,
          A5: "Kiwi", B5: 2.0, C5: 25,
          F1: "Lookup", G1: "Result", F2: "Kiwi", G2: "",
        },
        targetCell: "G2",
        expected: 25,
        hint: "Column index 3 returns the Stock column.",
        solution: "=VLOOKUP(F2, A2:C5, 3, FALSE)",
        i18n: {
          es: { title: "Encontrar el stock", prompt: 'En G2, usa VLOOKUP para encontrar el stock (columna 3) de la fruta en F2 desde A2:C5, coincidencia exacta.', hint: "La columna 3 devuelve la columna Stock." },
          id: { title: "Temukan stok", prompt: 'Di G2, gunakan VLOOKUP untuk menemukan stok (kolom 3) buah di F2 dari A2:C5, kecocokan tepat.', hint: "Kolom 3 mengembalikan kolom Stok." },
          fr: { title: "Trouver le stock", prompt: 'Dans G2, utilise VLOOKUP pour trouver le stock (colonne 3) du fruit en F2 depuis A2:C5, correspondance exacte.', hint: "La colonne 3 renvoie la colonne Stock." },
        },
      },
      {
        id: "l5p3",
        title: "Horizontal lookup",
        prompt: 'In cell H2, use HLOOKUP to find the Price (row 2) of the fruit named in G2 from the table A1:E3, exact match.',
        grid: {
          A1: "Fruit", B1: "Apple", C1: "Pear", D1: "Plum", E1: "Kiwi",
          A2: "Price", B2: 1.2, C2: 1.5, D2: 0.9, E2: 2.0,
          A3: "Stock", B3: 50, C3: 30, D3: 80, E3: 25,
          G1: "Lookup", H1: "Result", G2: "Pear", H2: "",
        },
        targetCell: "H2",
        expected: 1.5,
        hint: "=HLOOKUP(G2, A1:E3, 2, FALSE)",
        solution: "=HLOOKUP(G2, A1:E3, 2, FALSE)",
        i18n: {
          es: { title: "Búsqueda horizontal", prompt: 'En H2, usa HLOOKUP para encontrar el Precio (fila 2) de la fruta en G2 desde la tabla A1:E3, coincidencia exacta.', hint: "=HLOOKUP(G2, A1:E3, 2, FALSE)" },
          id: { title: "Pencarian mendatar", prompt: 'Di H2, gunakan HLOOKUP untuk menemukan Harga (baris 2) buah di G2 dari tabel A1:E3, kecocokan tepat.', hint: "=HLOOKUP(G2, A1:E3, 2, FALSE)" },
          fr: { title: "Recherche horizontale", prompt: 'Dans H2, utilise HLOOKUP pour trouver le Prix (ligne 2) du fruit en G2 dans le tableau A1:E3, correspondance exacte.', hint: "=HLOOKUP(G2, A1:E3, 2, FALSE)" },
        },
      },
      {
        id: "l5p4",
        title: "INDEX-MATCH",
        prompt: 'In cell G2, use INDEX-MATCH to return the Price of the fruit in F2: MATCH finds the row in A2:A5, INDEX returns it from B2:B5.',
        grid: {
          A1: "Fruit", B1: "Price", C1: "Stock",
          A2: "Apple", B2: 1.2, C2: 50,
          A3: "Pear", B3: 1.5, C3: 30,
          A4: "Plum", B4: 0.9, C4: 80,
          A5: "Kiwi", B5: 2.0, C5: 25,
          F1: "Lookup", G1: "Result", F2: "Pear", G2: "",
        },
        targetCell: "G2",
        expected: 1.5,
        hint: "=INDEX(B2:B5, MATCH(F2, A2:A5, 0))",
        solution: "=INDEX(B2:B5, MATCH(F2, A2:A5, 0))",
        i18n: {
          es: { title: "INDEX-MATCH", prompt: 'En G2, usa INDEX-MATCH para devolver el Precio de la fruta en F2: MATCH encuentra la fila en A2:A5 e INDEX la devuelve desde B2:B5.', hint: "=INDEX(B2:B5, MATCH(F2, A2:A5, 0))" },
          id: { title: "INDEX-MATCH", prompt: 'Di G2, gunakan INDEX-MATCH untuk mengembalikan Harga buah di F2: MATCH mencari barisnya di A2:A5, INDEX mengembalikannya dari B2:B5.', hint: "=INDEX(B2:B5, MATCH(F2, A2:A5, 0))" },
          fr: { title: "INDEX-MATCH", prompt: 'Dans G2, utilise INDEX-MATCH pour renvoyer le Prix du fruit en F2 : MATCH trouve la ligne dans A2:A5 et INDEX la renvoie depuis B2:B5.', hint: "=INDEX(B2:B5, MATCH(F2, A2:A5, 0))" },
        },
      },
    ],
    quizzes: [
      {
        id: "l5q1",
        type: "mc",
        prompt: "In VLOOKUP, what does the column index number control?",
        options: [
          "Which row to search",
          "Which column's value to return",
          "How many results to show",
          "The search direction",
        ],
        answer: 1,
        i18n: {
          es: { prompt: "En VLOOKUP, ¿qué controla el número de índice de columna?", options: ["Qué fila buscar", "Qué valor de columna devolver", "Cuántos resultados mostrar", "La dirección de búsqueda"] },
          id: { prompt: "Pada VLOOKUP, apa yang diatur oleh nomor indeks kolom?", options: ["Baris mana yang dicari", "Nilai kolom mana yang dikembalikan", "Berapa banyak hasil yang ditampilkan", "Arah pencarian"] },
          fr: { prompt: "Dans VLOOKUP, que contrôle le numéro d'index de colonne ?", options: ["Quelle ligne chercher", "Quelle valeur de colonne renvoyer", "Combien de résultats afficher", "Le sens de la recherche"] },
        },
      },
      {
        id: "l5q2",
        type: "mc",
        prompt: "For an exact match in VLOOKUP, the last argument should be:",
        options: ["TRUE", "FALSE", "0 only (never FALSE)", "LEFT"],
        answer: 1,
        i18n: {
          es: { prompt: "Para una coincidencia exacta en VLOOKUP, el último argumento debe ser:", options: ["TRUE", "FALSE", "solo 0 (nunca FALSE)", "LEFT"] },
          id: { prompt: "Untuk kecocokan tepat pada VLOOKUP, argumen terakhir harus:", options: ["TRUE", "FALSE", "hanya 0 (tidak pernah FALSE)", "LEFT"] },
          fr: { prompt: "Pour une correspondance exacte dans VLOOKUP, le dernier argument doit être :", options: ["TRUE", "FALSE", "seulement 0 (jamais FALSE)", "LEFT"] },
        },
      },
      {
        id: "l5q3",
        type: "write",
        title: "Look up stock",
        prompt: 'In cell G2, use VLOOKUP to return the Stock (column 3) for the fruit in F2 from A2:C5 (exact match).',
        grid: {
          A1: "Fruit", B1: "Price", C1: "Stock",
          A2: "Apple", B2: 1.2, C2: 50,
          A3: "Pear", B3: 1.5, C3: 30,
          A4: "Plum", B4: 0.9, C4: 80,
          A5: "Kiwi", B5: 2.0, C5: 25,
          F1: "Lookup", G1: "Result", F2: "Plum", G2: "",
        },
        targetCell: "G2",
        expected: 80,
        solution: "=VLOOKUP(F2, A2:C5, 3, FALSE)",
        i18n: {
          es: { title: "Buscar stock", prompt: 'En G2, usa VLOOKUP para devolver el Stock (columna 3) de la fruta en F2 desde A2:C5 (coincidencia exacta).' },
          id: { title: "Cari stok", prompt: 'Di G2, gunakan VLOOKUP untuk mengembalikan Stok (kolom 3) buah di F2 dari A2:C5 (kecocokan tepat).' },
          fr: { title: "Trouver le stock", prompt: 'Dans G2, utilise VLOOKUP pour renvoyer le Stock (colonne 3) du fruit en F2 depuis A2:C5 (correspondance exacte).' },
        },
      },
      {
        id: "l5q4",
        type: "write",
        title: "HLOOKUP the stock",
        prompt: 'In cell H2, use HLOOKUP to return the Stock (row 3) of the fruit in G2 from A1:E3 (exact match).',
        grid: {
          A1: "Fruit", B1: "Apple", C1: "Pear", D1: "Plum", E1: "Kiwi",
          A2: "Price", B2: 1.2, C2: 1.5, D2: 0.9, E2: 2.0,
          A3: "Stock", B3: 50, C3: 30, D3: 80, E3: 25,
          G1: "Lookup", H1: "Result", G2: "Kiwi", H2: "",
        },
        targetCell: "H2",
        expected: 25,
        solution: "=HLOOKUP(G2, A1:E3, 3, FALSE)",
        i18n: {
          es: { title: "Stock con HLOOKUP", prompt: 'En H2, usa HLOOKUP para devolver el Stock (fila 3) de la fruta en G2 desde A1:E3 (coincidencia exacta).' },
          id: { title: "Stok dengan HLOOKUP", prompt: 'Di H2, gunakan HLOOKUP untuk mengembalikan Stok (baris 3) buah di G2 dari A1:E3 (kecocokan tepat).' },
          fr: { title: "Stock avec HLOOKUP", prompt: 'Dans H2, utilise HLOOKUP pour renvoyer le Stock (ligne 3) du fruit en G2 depuis A1:E3 (correspondance exacte).' },
        },
      },
      {
        id: "l5q5",
        type: "write",
        title: "INDEX-MATCH the stock",
        prompt: 'In cell G2, use INDEX-MATCH to return the Stock of the fruit in F2: MATCH the row in A2:A5, INDEX from C2:C5.',
        grid: {
          A1: "Fruit", B1: "Price", C1: "Stock",
          A2: "Apple", B2: 1.2, C2: 50,
          A3: "Pear", B3: 1.5, C3: 30,
          A4: "Plum", B4: 0.9, C4: 80,
          A5: "Kiwi", B5: 2.0, C5: 25,
          F1: "Lookup", G1: "Result", F2: "Plum", G2: "",
        },
        targetCell: "G2",
        expected: 80,
        solution: "=INDEX(C2:C5, MATCH(F2, A2:A5, 0))",
        i18n: {
          es: { title: "Stock con INDEX-MATCH", prompt: 'En G2, usa INDEX-MATCH para devolver el Stock de la fruta en F2: MATCH la fila en A2:A5, INDEX desde C2:C5.' },
          id: { title: "Stok dengan INDEX-MATCH", prompt: 'Di G2, gunakan INDEX-MATCH untuk mengembalikan Stok buah di F2: MATCH barisnya di A2:A5, INDEX dari C2:C5.' },
          fr: { title: "Stock avec INDEX-MATCH", prompt: 'Dans G2, utilise INDEX-MATCH pour renvoyer le Stock du fruit en F2 : MATCH la ligne dans A2:A5, INDEX depuis C2:C5.' },
        },
      },
      {
        id: "l5q6",
        type: "mc",
        prompt: "What is a key advantage of INDEX-MATCH over VLOOKUP?",
        options: [
          "It is always slower",
          "It can look up a value to the LEFT of the lookup column",
          "It only works with numbers",
          "It needs four arguments",
        ],
        answer: 1,
        i18n: {
          es: { prompt: "¿Cuál es una ventaja clave de INDEX-MATCH sobre VLOOKUP?", options: ["Siempre es más lento", "Puede buscar un valor a la IZQUIERDA de la columna de búsqueda", "Solo funciona con números", "Necesita cuatro argumentos"] },
          id: { prompt: "Apa keuntungan utama INDEX-MATCH dibanding VLOOKUP?", options: ["Selalu lebih lambat", "Dapat mencari nilai di KIRI kolom pencarian", "Hanya bekerja dengan angka", "Membutuhkan empat argumen"] },
          fr: { prompt: "Quel est un avantage clé d'INDEX-MATCH par rapport à VLOOKUP ?", options: ["Il est toujours plus lent", "Il peut rechercher une valeur à GAUCHE de la colonne de recherche", "Il ne fonctionne qu'avec des nombres", "Il faut quatre arguments"] },
        },
      },
    ],
  },

  {
    id: 6,
    name: "Stats & Criteria",
    icon: "📊",
    tagline: "Count and sum only the rows that matter.",
    formulas: [
      {
        name: "COUNTIF",
        syntax: '=COUNTIF(range, criteria)',
        description: 'Counts cells that meet a condition, e.g. ">5" or "apple".',
        example: '=COUNTIF(A1:A10, ">5")',
        result: "Counts cells in A1:A10 that are greater than 5.",
        i18n: {
          es: { description: 'Cuenta celdas que cumplen una condición, p. ej. ">5" o "manzana".', result: "Cuenta las celdas de A1:A10 que son mayores que 5." },
          id: { description: 'Menghitung sel yang memenuhi kondisi, mis. ">5" atau "apel".', result: "Menghitung sel di A1:A10 yang lebih besar dari 5." },
          fr: { description: 'Compte les cellules qui remplissent une condition, ex. ">5" ou "pomme".', result: "Compte les cellules de A1:A10 supérieures à 5." },
        },
      },
      {
        name: "COUNTIFS",
        syntax: "=COUNTIFS(range1, crit1, [range2, crit2], ...)",
        description: "Counts rows that meet several conditions at once.",
        example: '=COUNTIFS(A1:A10, ">5", B1:B10, "x")',
        result: 'Counts rows where A is >5 and B is "x".',
        i18n: {
          es: { description: "Cuenta filas que cumplen varias condiciones a la vez.", result: 'Cuenta las filas donde A es >5 y B es "x".' },
          id: { description: "Menghitung baris yang memenuhi beberapa kondisi sekaligus.", result: 'Menghitung baris di mana A >5 dan B adalah "x".' },
          fr: { description: "Compte les lignes qui remplissent plusieurs conditions à la fois.", result: 'Compte les lignes où A > 5 et B vaut "x".' },
        },
      },
      {
        name: "SUMIF",
        syntax: "=SUMIF(range, criteria, [sum_range])",
        description: "Adds up cells that meet a condition.",
        example: '=SUMIF(A1:A10, ">5", B1:B10)',
        result: "Sums column B where column A is greater than 5.",
        i18n: {
          es: { description: "Suma las celdas que cumplen una condición.", result: "Suma la columna B donde la columna A es mayor que 5." },
          id: { description: "Menjumlahkan sel yang memenuhi kondisi.", result: "Menjumlahkan kolom B di mana kolom A lebih besar dari 5." },
          fr: { description: "Additionne les cellules qui remplissent une condition.", result: "Additionne la colonne B où la colonne A est supérieure à 5." },
        },
      },
      {
        name: "AVERAGEIF",
        syntax: "=AVERAGEIF(range, criteria, [avg_range])",
        description: "Averages cells that meet a condition.",
        example: '=AVERAGEIF(A1:A10, ">5", B1:B10)',
        result: "Averages column B where column A is greater than 5.",
        i18n: {
          es: { description: "Promedia las celdas que cumplen una condición.", result: "Promedia la columna B donde la columna A es mayor que 5." },
          id: { description: "Merata-rata sel yang memenuhi kondisi.", result: "Merata-rata kolom B di mana kolom A lebih besar dari 5." },
          fr: { description: "Fait la moyenne des cellules qui remplissent une condition.", result: "Fait la moyenne de la colonne B où la colonne A est supérieure à 5." },
        },
      },
      {
        name: "MEDIAN",
        syntax: "=MEDIAN(number1, [number2], ...)",
        description: "Returns the middle value of a set of numbers when sorted.",
        example: "=MEDIAN(A1:A5)",
        result: "The middle number once the values are sorted.",
        i18n: {
          es: { description: "Devuelve el valor del medio de un conjunto de números ordenados.", result: "El número del medio una vez ordenados los valores." },
          id: { description: "Mengembalikan nilai tengah dari kumpulan angka yang diurutkan.", result: "Nilai tengah setelah angka diurutkan." },
          fr: { description: "Renvoie la valeur médiane d'un ensemble de nombres triés.", result: "Le nombre du milieu une fois les valeurs triées." },
        },
      },
    ],
    practices: [
      {
        id: "l6p1",
        title: "Count the high scores",
        prompt: "In cell B2, count how many scores in A2:A6 are greater than 80.",
        grid: { A1: "Score", B1: "Count", A2: 90, A3: 75, A4: 88, A5: 60, A6: 95, B2: "" },
        targetCell: "B2",
        expected: 3,
        hint: "Put the > inside quotes: \">80\".",
        solution: '=COUNTIF(A2:A6, ">80")',
        i18n: {
          es: { title: "Cuenta las notas altas", prompt: "En B2, cuenta cuántas notas en A2:A6 son mayores que 80.", hint: 'Pon el > entre comillas: ">80".' },
          id: { title: "Hitung skor tinggi", prompt: "Di B2, hitung berapa banyak skor di A2:A6 yang lebih besar dari 80.", hint: 'Letakkan > di dalam tanda kutip: ">80".' },
          fr: { title: "Compte les hauts scores", prompt: "Dans B2, compte combien de notes en A2:A6 sont supérieures à 80.", hint: 'Place le > entre guillemets : ">80".' },
        },
      },
      {
        id: "l6p2",
        title: "Sum the big ones",
        prompt: "In cell B7, total the sales in B2:B6 where the score in A2:A6 is at least 80.",
        grid: { A1: "Score", B1: "Sales", A2: 90, B2: 200, A3: 75, B3: 150, A4: 88, B4: 120, A5: 60, B5: 80, A6: 95, B6: 300, B7: "" },
        targetCell: "B7",
        expected: 620,
        hint: "SUMIF(range, criteria, sum_range).",
        solution: '=SUMIF(A2:A6, ">=80", B2:B6)',
        i18n: {
          es: { title: "Suma las grandes", prompt: "En B7, suma las ventas en B2:B6 donde la nota en A2:A6 es al menos 80.", hint: "SUMIF(rango, criterio, rango_suma)." },
          id: { title: "Jumlahkan yang besar", prompt: "Di B7, totalkan penjualan di B2:B6 di mana skor di A2:A6 minimal 80.", hint: "SUMIF(rantang, kriteria, rentang_jumlah)." },
          fr: { title: "Somme des grandes", prompt: "Dans B7, additionne les ventes en B2:B6 où la note en A2:A6 est d'au moins 80.", hint: "SUMIF(plage, critère, plage_somme)." },
        },
      },
      {
        id: "l6p3",
        title: "Average the A's",
        prompt: "In cell B7, average the prices in B2:B6 where the grade in A2:A6 is 'A'.",
        grid: { A1: "Grade", B1: "Price", A2: "A", B2: 10, A3: "B", B3: 8, A4: "A", B4: 12, A5: "A", B5: 9, A6: "B", B6: 7, B7: "" },
        targetCell: "B7",
        expected: 31 / 3,
        hint: "AVERAGEIF(range, criteria, avg_range).",
        solution: '=AVERAGEIF(A2:A6, "A", B2:B6)',
        i18n: {
          es: { title: "Promedia las A", prompt: "En B7, promedia los precios en B2:B6 donde la nota en A2:A6 es 'A'.", hint: "AVERAGEIF(rango, criterio, rango_prom).", solution: '=AVERAGEIF(A2:A6, "A", B2:B6)' },
          id: { title: "Rata-rata A", prompt: "Di B7, rata-ratakan harga di B2:B6 di mana nilai di A2:A6 adalah 'A'.", hint: "AVERAGEIF(rantang, kriteria, rentang_rata).", solution: '=AVERAGEIF(A2:A6, "A", B2:B6)' },
          fr: { title: "Moyenne des A", prompt: "Dans B7, fais la moyenne des prix en B2:B6 où la note en A2:A6 est 'A'.", hint: "AVERAGEIF(plage, critère, plage_moy).", solution: '=AVERAGEIF(A2:A6, "A", B2:B6)' },
        },
      },
      {
        id: "l6p4",
        title: "Middle value",
        prompt: "In cell B2, find the median of the values in A2:A6.",
        grid: { A1: "Value", B1: "Median", A2: 5, A3: 1, A4: 9, A5: 3, A6: 7, B2: "" },
        targetCell: "B2",
        expected: 5,
        hint: "MEDIAN ignores order and picks the middle.",
        solution: "=MEDIAN(A2:A6)",
        i18n: {
          es: { title: "Valor del medio", prompt: "En B2, encuentra la mediana de los valores en A2:A6.", hint: "MEDIAN ignora el orden y elige el del medio." },
          id: { title: "Nilai tengah", prompt: "Di B2, temukan median dari nilai-nilai di A2:A6.", hint: "MEDIAN mengabaikan urutan dan memilih yang tengah." },
          fr: { title: "Valeur médiane", prompt: "Dans B2, trouve la médiane des valeurs en A2:A6.", hint: "MEDIAN ignore l'ordre et prend la valeur du milieu." },
        },
      },
      {
        id: "l6p5",
        title: "Two conditions",
        prompt: "In cell B2, count rows where the score in A2:A6 is at least 80 AND the zone in C2:C6 is 'North'.",
        grid: { A1: "Score", C1: "Zone", B1: "Count", A2: 90, C2: "North", A3: 75, C3: "South", A4: 88, C4: "North", A5: 60, C5: "North", A6: 95, C6: "South", B2: "" },
        targetCell: "B2",
        expected: 2,
        hint: "COUNTIFS(range1, crit1, range2, crit2).",
        solution: '=COUNTIFS(A2:A6, ">=80", C2:C6, "North")',
        i18n: {
          es: { title: "Dos condiciones", prompt: "En B2, cuenta las filas donde la nota en A2:A6 es al menos 80 Y la zona en C2:C6 es 'North'.", hint: "COUNTIFS(rango1, crit1, rango2, crit2)." },
          id: { title: "Dua kondisi", prompt: "Di B2, hitung baris di mana skor di A2:A6 minimal 80 DAN zona di C2:C6 adalah 'North'.", hint: "COUNTIFS(rantang1, krit1, rantang2, krit2)." },
          fr: { title: "Deux conditions", prompt: "Dans B2, compte les lignes où la note en A2:A6 est d'au moins 80 ET la zone en C2:C6 vaut 'North'.", hint: "COUNTIFS(plage1, crit1, plage2, crit2)." },
        },
      },
    ],
    quizzes: [
      {
        id: "l6q1",
        type: "mc",
        prompt: 'What does =COUNTIF(A1:A10, ">5") count?',
        options: ["Cells equal to 5", "Cells greater than 5", "Cells less than 5", "All non-empty cells"],
        answer: 1,
        i18n: {
          es: { prompt: '¿Qué cuenta =COUNTIF(A1:A10, ">5")?' },
          id: { prompt: 'Apa yang dihitung =COUNTIF(A1:A10, ">5")?' },
          fr: { prompt: 'Que compte =COUNTIF(A1:A10, ">5") ?' },
        },
      },
      {
        id: "l6q2",
        type: "mc",
        prompt: "Compared to COUNTIF, what extra argument does SUMIF need?",
        options: ["A sum range", "A second criterion", "Nothing extra", "A column index"],
        answer: 0,
        i18n: {
          es: { prompt: "En comparación con COUNTIF, ¿qué argumento extra necesita SUMIF?" },
          id: { prompt: "Dibanding COUNTIF, argumen apa yang dibutuhkan tambahan oleh SUMIF?" },
          fr: { prompt: "Par rapport à COUNTIF, quel argument supplémentaire SUMIF nécessite-t-il ?" },
        },
      },
      {
        id: "l6q3",
        type: "write",
        title: "Count the A's",
        prompt: "In cell B2, count how many grades in A2:A6 are 'A'.",
        grid: { A1: "Grade", B1: "Count", A2: "A", A3: "B", A4: "A", A5: "C", A6: "A", B2: "" },
        targetCell: "B2",
        expected: 3,
        solution: '=COUNTIF(A2:A6, "A")',
        i18n: {
          es: { title: "Cuenta las A", prompt: "En B2, cuenta cuántas notas en A2:A6 son 'A'.", solution: '=COUNTIF(A2:A6, "A")' },
          id: { title: "Hitung A", prompt: "Di B2, hitung berapa banyak nilai di A2:A6 adalah 'A'.", solution: '=COUNTIF(A2:A6, "A")' },
          fr: { title: "Compte les A", prompt: "Dans B2, compte combien de notes en A2:A6 sont 'A'.", solution: '=COUNTIF(A2:A6, "A")' },
        },
      },
    ],
  },
];

const PASS_THRESHOLD = 0.8; // 80% to level up
const XP_PER_QUIZ = 50;
const XP_PER_PRACTICE = 10;
